//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe_management_system_A1
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int OrderId { get; set; }
        public string ItemName { get; set; }
        public int UserID { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual user user { get; set; }
    }
}
